[build]
builder = "DOCKERFILE"
buildCommand = "bun run build"

[deploy]
numReplicas = 1
startCommand = "nginx -g 'daemon off;'"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 1000

[nixpacks]
disable = true 