[build]
builder = "nixpacks"
nixpacksVersion = "1.15.0"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Define separate services
[services.web]
name = "web"
startCommand = "cd apps/web && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 10
healthcheckInterval = 30

[services.api]
name = "backend"
startCommand = "cd apps/backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 10
healthcheckInterval = 30

[services.relay]
name = "relay"
startCommand = "cd apps/relay && go run main.go"

[services.dvm]
name = "dvm"
startCommand = "cd apps/dvm && npm start" 